server:
  port: 9002

spring:
  security:
    oauth2:
      client:
        registration:
          wordpress:
            provider:                     "wordpress"
            client-name:                  "Wordpress"
            client-id:                    "[env]"
            client-secret:                "[env]"
            authorization-grant-type:     "authorization_code"
            client-authentication-method: "POST"
            redirect-uri:                 "{baseUrl}/login/oauth2/code/{registrationId}"
        provider: 
          wordpress:
            authorization-uri:   "https://public-api.wordpress.com/oauth2/authorize"
            token-uri:           "https://public-api.wordpress.com/oauth2/token"
            user-info-uri:       "https://public-api.wordpress.com/rest/v1.1/me"
  profiles:
    active:
    - dev
    - ssl

logging:
  level:    root: WARN
    com.example.spring.yconnect: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG