server:
  port: 9002
  ssl:
    key-store:          "classpath:keystore.p12"
    key-store-password: "12345678"
    key-store-type:     "PKCS12"
    key-alias:          "tomcat"

# env settings
# spring.security.oauth2.client.registration.wordpress.client-id
# spring.security.oauth2.client.registration.wordpress.client-secret

spring:
  thymeleaf:    cache: false
    enabled: true
    encoding: "UTF-8"
    
  security:
    oauth2:
      client:
        registration:
          wordpress:
            provider:                       "wordpress"
            client-name:                    "Wordpress"
            
            client-id:                      "[env]"
            client-secret:                  "[env]"
            redirect-uri:                   "{baseUrl}/login/oauth2/code/{registrationId}"
            
            # fixed
            authorization-grant-type:       "authorization_code"
            client-authentication-method:   "post"
        provider: 
          wordpress:
            authorization-uri: "https://public-api.wordpress.com/oauth2/authorize"
            token-uri:         "https://public-api.wordpress.com/oauth2/token"
            user-info-uri:     "https://public-api.wordpress.com/rest/v1.1/me"

logging:
  level:
    com.example: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG